/**
 * Ticker → company name for tiles and search. The registry only stores the symbol on-chain.
 * Names from https://docs.robinhood.com/chain/contracts/ ; unknown tickers fall back to the symbol
 * (a handful of newer / private-company tickers are deliberately left unmapped rather than guessed).
 *
 * Icons: an SVG at apps/web/public/tickers/<TICKER>.svg shows a logo (shared with the $PIE project);
 * the UI falls back to the ticker's letters on a lime disc when the file is missing.
 */
export const TICKER_NAMES: Record<string, string> = {
  AAPL: "Apple",
  NVDA: "NVIDIA",
  GOOGL: "Alphabet Class A",
  MSFT: "Microsoft",
  AMZN: "Amazon",
  TSLA: "Tesla",
  AMD: "AMD",
  META: "Meta Platforms",
  AVGO: "Broadcom",
  NFLX: "Netflix",
  COIN: "Coinbase",
  PLTR: "Palantir Technologies",
  MSTR: "Strategy Inc.",
  TSM: "Taiwan Semiconductor",
  INTC: "Intel",
  MU: "Micron Technology",
  ORCL: "Oracle",
  CRM: "Salesforce",
  ADBE: "Adobe",
  QQQ: "Invesco QQQ",
  SPY: "SPDR S&P 500 ETF",
  IBM: "IBM",
  BABA: "Alibaba",
  ASML: "ASML Holding",
  UNH: "UnitedHealth",
  XOM: "ExxonMobil",
  JNJ: "Johnson & Johnson",
  PFE: "Pfizer",
  LLY: "Eli Lilly",
  CSCO: "Cisco Systems",
  QCOM: "Qualcomm",
  SHOP: "Shopify",
  SNOW: "Snowflake",
  RBLX: "Roblox",
  HOOD: "Robinhood Markets",
  COST: "Costco Wholesale",
  AEIS: "Advanced Energy Industries",
  AMAT: "Applied Materials",
  AMBA: "Ambarella",
  AMC: "AMC Entertainment",
  AMKR: "Amkor Technology",
  ANET: "Arista Networks",
  APP: "AppLovin",
  ASTS: "AST SpaceMobile",
  AVAV: "AeroVironment",
  AXON: "Axon Enterprise",
  BA: "Boeing",
  BB: "BlackBerry",
  BE: "Bloom Energy",
  CCL: "Carnival Corporation",
  CEG: "Constellation Energy",
  CELH: "Celsius Holdings",
  COHR: "Coherent Corp",
  CRWD: "CrowdStrike",
  CRWV: "CoreWeave",
  CTSH: "Cognizant Technology Solutions",
  DELL: "Dell Technologies",
  DJT: "Trump Media & Technology Group",
  DOCN: "DigitalOcean",
  EWT: "iShares MSCI Taiwan ETF",
  EWY: "iShares MSCI South Korea ETF",
  F: "Ford Motor",
  FICO: "Fair Isaac",
  FIG: "Figma",
  FISV: "Fiserv",
  FIX: "Comfort Systems USA",
  FTNT: "Fortinet",
  GE: "GE Aerospace",
  GEV: "GE Vernova",
  GLD: "SPDR Gold Shares",
  GLW: "Corning",
  GME: "GameStop",
  HII: "Huntington Ingalls Industries",
  HIMS: "Hims & Hers Health",
  HPE: "Hewlett Packard Enterprise",
  HWM: "Howmet Aerospace",
  INDA: "iShares MSCI India ETF",
  INTU: "Intuit",
  IONQ: "IonQ",
  IREN: "IREN Limited",
  JBL: "Jabil",
  KLAC: "KLA Corporation",
  KSS: "Kohl's",
  LHX: "L3Harris Technologies",
  LITE: "Lumentum Holdings",
  LMT: "Lockheed Martin",
  LRCX: "Lam Research",
  LULU: "Lululemon Athletica",
  LUNR: "Intuitive Machines",
  MDB: "MongoDB",
  MOD: "Modine Manufacturing",
  MPWR: "Monolithic Power Systems",
  MRNA: "Moderna",
  MRVL: "Marvell Technology",
  MTSI: "MACOM Technology Solutions",
  MXL: "MaxLinear",
  NET: "Cloudflare",
  NOW: "ServiceNow",
  NU: "Nu Holdings",
  ON: "ON Semiconductor",
  ONTO: "Onto Innovation",
  PANW: "Palo Alto Networks",
  PATH: "UiPath",
  PL: "Planet Labs",
  QBTS: "D-Wave Quantum",
  RDDT: "Reddit",
  RDW: "Redwire",
  RGTI: "Rigetti Computing",
  RIVN: "Rivian Automotive",
  RKLB: "Rocket Lab",
  RUN: "Sunrun",
  SATS: "EchoStar",
  SCHD: "Schwab US Dividend Equity ETF",
  SGOV: "iShares 0-3 Month Treasury Bond ETF",
  SHY: "iShares 1-3 Year Treasury Bond ETF",
  SIMO: "Silicon Motion Technology",
  SLV: "iShares Silver Trust",
  SMCI: "Super Micro Computer",
  SMH: "VanEck Semiconductor ETF",
  SNAP: "Snap",
  SNDK: "Sandisk",
  SOFI: "SoFi Technologies",
  SOXX: "iShares Semiconductor ETF",
  SPCX: "SpaceX",
  TEAM: "Atlassian",
  TEM: "Tempus AI",
  TER: "Teradyne",
  TSEM: "Tower Semiconductor",
  TTD: "The Trade Desk",
  TTWO: "Take-Two Interactive",
  UMC: "United Microelectronics",
  UPS: "United Parcel Service",
  VRT: "Vertiv Holdings",
  VSAT: "Viasat",
  VST: "Vistra",
  WDAY: "Workday",
  WDC: "Western Digital",
  XLK: "Technology Select Sector SPDR Fund",
  ZM: "Zoom Communications",
};

export const tickerName = (symbol: string) => TICKER_NAMES[symbol.toUpperCase()] ?? symbol;
export const tickerIconUrl = (symbol: string) => `/tickers/${symbol.toUpperCase()}.svg`;
